### PR TITLE
Fix formatting for namespaced maps

### LINKED ISSUE #6: Maps with default namespaces aren't indented correctly
```
$ cljfmt check foo.clj 
--- a/foo.clj
+++ b/foo.clj
@@ -1,5 +1,5 @@
 (ns foo)
 
 
-(def bar #:asdf{:one 1
+(def bar #:asdf {:one 1
                 :two 2})
1 files formatted incorrectly
$ cat foo.clj
(ns foo)


(def bar #:asdf{:one 1
                :two 2})
```

Currently it inserts a space between the default namespace and the map, but doesn't indent the map to match.

It should either insert a space and indent the map or do nothing.

Version 0.8.1.

### PR DESCRIPTION
**Pull request by drewinglis**
Fixes #6.

We weren't writing anything for the `start-element` for the `:namespaced-map` node, which means that we weren't accounting for it in the indentation for any subsequent lines.

See also: https://github.com/xsc/rewrite-clj/pull/66

### CODE REVIEW

File: core/src/cljfmt/format/core.clj [hunk 1]
```diff
@@ -236,7 +236,11 @@
   [zloc]
   (and (zl/element? zloc)
        (not (zl/reader-macro? (zip/up zloc)))
-       (zl/element? (zip/right zloc))))
+       (zl/element? (zip/right zloc))
+       (not (= :namespaced-map (-> zloc
```
Comment (greglook) [inline core/src/cljfmt/format/core.clj]: 🏌 `(not (= x y))` => `(not= x y)`

File: core/test/cljfmt/format/core_test.clj [hunk 2]
```diff
@@ -172,7 +183,7 @@
     (is (= "#inst\n\"2018-01-01T00:00:00.000-00:00\""
            (reformat-string "#inst\n\"2018-01-01T00:00:00.000-00:00\""))))
   (testing "map prefixes"
-    (is (= "#:abc\n{:d 1}"
+    (is (= "#:abc\n {:d 1}"
```
Comment (greglook) [inline core/test/cljfmt/format/core_test.clj]: Could you move this next to the other map tests? This also doesn't seem right, it's saying that this would be indented like:
```clojure
#:abc
 {:d 1}
```
The map body should be aligned with the tag if there's a line-break.

Comment (drewinglis) [reply core/test/cljfmt/format/core_test.clj]: The map body is aligned with the tag. :^)

More seriously, there are three separate arguments here I'll make:
1. I'm not convinced that this format is wrong. Philosophically, if you treat the `#` as opening a `:namespaced-map` form, it makes sense that the form body should be indented to match (like how you indent a normal `:map` form: `{:a 1\n :b 2}`).
2. This is how the weavejester implementation formats this. I'm not sure how big a goal compatibility is to you.
3. I don't think we have enough information with the current data structures to fix this problem. For multiline inner maps, to format them "correctly", you would need to check to see if you're also in a `:namespaced-map`, and also if the first line of the `:namespaced-map` is inline or on a new line, and then only indent in the first case.

Comment (drewinglis) [reply core/test/cljfmt/format/core_test.clj]: Happy to chat in person, also.

Comment (drewinglis) [reply core/test/cljfmt/format/core_test.clj]: Maybe we could just do the change to `core.clj`? That would fix the indentation for abutting maps without screwing up indentation to maps that don't have the first element on the same line as the keyword.

Comment (drewinglis) [reply core/test/cljfmt/format/core_test.clj]: Fixed.

**Comment by drewinglis** [comment]
I finally patched this up, and it is ready for re-review.

File: core/test/cljfmt/format/core_test.clj [hunk 3]
```diff
@@ -23,6 +23,23 @@
...
 
 
+(deftest namespaced-maps
+  (is (= "#:a{:one 1\n    :two 2}"
+         (reformat-string "#:a{:one 1\n    :two 2}")))
+  (is (= "#:a{:one 1\n    :two 2}"
+         (reformat-string "#:a{:one 1\n    :two 2}" {:insert-missing-whitespace? false})))
+  (is (= "#:a {:one 1\n     :two 2}"
+         (reformat-string "#:a {:one 1\n     :two 2}")))
+  (is (= "#:a {:one 1\n     :two 2}"
```
Comment (greglook) [inline core/test/cljfmt/format/core_test.clj]: What happens when there is more than one space between the map namespace and the opening brace?

Comment (drewinglis) [reply core/test/cljfmt/format/core_test.clj]: It doesn't remove the space. Should I open up another issue for that?

**Comment by drewinglis** [comment]
Oh, I don't have write access to your repository so I can't merge. But if you do merge, please squash me. :)
